# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Yankey/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-1660-DESKTOP-8DCGADD/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.cache/wt [current_project]
set_property parent.project_path C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/2WSsP_2InputMux_32.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/7inputMux.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/ALU.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/CLA32Adder.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/Cause1Flop.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/ControlUnit.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/DE_pipe_REG.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/DataMemory.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/Datapath.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/EM_pipe_REG.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/Exception_2.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/FD_pipe_REG.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/HazardUnit.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/MW_pipe_REG.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/PCWrite.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/PCmUX.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/SuperScalarProcessor.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/Two_Issue_Scheduler.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/Two_port_simple_ROM.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/aluDEC.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/andGate.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/comparator.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/eight_input_Mux.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/four_Input_Mux.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/generic_2_input_mux.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/generic_Control.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/mainDEC.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/mux_5select.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/notGate.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/orGate.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/pcFlopr.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/registerFile.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/shiftLeft2.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/signExtender.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/xorGate.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/zeroExtender.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/Top_MemoryInterface.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/sllGate.vhd
  C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/srlGate.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top_MemoryInterface -part xc7a35tcpg236-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_MemoryInterface.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_MemoryInterface_utilization_synth.rpt -pb Top_MemoryInterface_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
