webtalk_init -webtalk_dir /home/sweet12prof/Desktop/2ISSP_v2/TwoIssueSuperscalar_v2.sim/sim_1/behav/xsim/xsim.dir/Top_MemoryInterface_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 13 12:19:31 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2729669" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "76841301-a584-4594-81cf-1c0383d1ee9b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3c3f759be5ef42ba93e4ec9762751962" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3463.671 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3308690 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "9.47_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "133748_KB" -context "xsim\\usage"
webtalk_transmit -clientid 499812208 -regid "" -xml /home/sweet12prof/Desktop/2ISSP_v2/TwoIssueSuperscalar_v2.sim/sim_1/behav/xsim/xsim.dir/Top_MemoryInterface_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/sweet12prof/Desktop/2ISSP_v2/TwoIssueSuperscalar_v2.sim/sim_1/behav/xsim/xsim.dir/Top_MemoryInterface_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/sweet12prof/Desktop/2ISSP_v2/TwoIssueSuperscalar_v2.sim/sim_1/behav/xsim/xsim.dir/Top_MemoryInterface_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
