# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/.Xil/Vivado-6232-DESKTOP-8DCGADD/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-2L
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::enableVHDL2008 1
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/2WSsP_2InputMux_32.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/7inputMux.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/ALU.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/CLA32Adder.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/ControlUnit.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/DE_pipe_REG.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/DataMemory.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/Datapath.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/EM_pipe_REG.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/FD_pipe_REG.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/HazardUnit.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/MW_pipe_REG.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/PCmUX.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/SuperScalarProcessor.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/Two_Issue_Scheduler.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/Two_port_simple_ROM.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/aluDEC.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/andGate.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/comparator.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/eight_input_Mux.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/four_Input_Mux.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/generic_2_input_mux.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/generic_Control.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/mainDEC.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/notGate.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/orGate.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/pcFlopr.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/registerFile.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/shiftLeft2.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/signExtender.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/xorGate.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/zeroExtender.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/Top_MemoryInterface.vhd
    }
      rt::read_vhdl -vhdl2008 -lib xil_defaultlib {
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/sllGate.vhd
      C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/TwoIssueSuperscalar_v2.srcs/sources_1/new/srlGate.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top Top_MemoryInterface
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/Yankey/Desktop/Projects/MasterScalar/2ISSP_v2/.Xil/Vivado-6232-DESKTOP-8DCGADD/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
